//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSS.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValueParas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValueParas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDSS.Resource.ValueParas", typeof(ValueParas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 丙氨酸氨基转移酶.
        /// </summary>
        internal static string AlanineAminotransferase {
            get {
                return ResourceManager.GetString("AlanineAminotransferase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alb/Cr.
        /// </summary>
        internal static string ALBCR {
            get {
                return ResourceManager.GetString("ALBCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天冬氨酸氨基转移酶.
        /// </summary>
        internal static string AspartateAminotransferase {
            get {
                return ResourceManager.GetString("AspartateAminotransferase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血氯.
        /// </summary>
        internal static string BCL {
            get {
                return ResourceManager.GetString("BCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血CO2CP.
        /// </summary>
        internal static string BCO2CP {
            get {
                return ResourceManager.GetString("BCO2CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机血糖.
        /// </summary>
        internal static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血钙.
        /// </summary>
        internal static string BGA {
            get {
                return ResourceManager.GetString("BGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血钾.
        /// </summary>
        internal static string BKA {
            get {
                return ResourceManager.GetString("BKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血钠.
        /// </summary>
        internal static string BNA {
            get {
                return ResourceManager.GetString("BNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血磷.
        /// </summary>
        internal static string BP {
            get {
                return ResourceManager.GetString("BP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血尿酸.
        /// </summary>
        internal static string BUA {
            get {
                return ResourceManager.GetString("BUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 肌酐.
        /// </summary>
        internal static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 舒张压1.
        /// </summary>
        internal static string DBP1 {
            get {
                return ResourceManager.GetString("DBP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 舒张压2.
        /// </summary>
        internal static string DBP2 {
            get {
                return ResourceManager.GetString("DBP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空腹C肽.
        /// </summary>
        internal static string FastingCPeptide {
            get {
                return ResourceManager.GetString("FastingCPeptide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空腹胰岛素.
        /// </summary>
        internal static string FastingInsulin {
            get {
                return ResourceManager.GetString("FastingInsulin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空腹血糖.
        /// </summary>
        internal static string FBG {
            get {
                return ResourceManager.GetString("FBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进餐主食数量.
        /// </summary>
        internal static string FoodCount {
            get {
                return ResourceManager.GetString("FoodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDA65.
        /// </summary>
        internal static string GDA65 {
            get {
                return ResourceManager.GetString("GDA65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HbA1c.
        /// </summary>
        internal static string HBA1C {
            get {
                return ResourceManager.GetString("HBA1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 臀围.
        /// </summary>
        internal static string HC {
            get {
                return ResourceManager.GetString("HC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDL-ch.
        /// </summary>
        internal static string HDLC {
            get {
                return ResourceManager.GetString("HDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身高.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脉(心)率.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICA.
        /// </summary>
        internal static string ICA {
            get {
                return ResourceManager.GetString("ICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDL-ch.
        /// </summary>
        internal static string LDLC {
            get {
                return ResourceManager.GetString("LDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尿酮体.
        /// </summary>
        internal static string NTT {
            get {
                return ResourceManager.GetString("NTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGTT空腹血糖.
        /// </summary>
        internal static string OGTTFBG {
            get {
                return ResourceManager.GetString("OGTTFBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGTT餐后血糖.
        /// </summary>
        internal static string OGTTPBG {
            get {
                return ResourceManager.GetString("OGTTPBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 餐后C肽.
        /// </summary>
        internal static string PostprandialCPeptide {
            get {
                return ResourceManager.GetString("PostprandialCPeptide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 餐后胰岛素.
        /// </summary>
        internal static string PostprandialInsulin {
            get {
                return ResourceManager.GetString("PostprandialInsulin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收缩压1.
        /// </summary>
        internal static string SBP1 {
            get {
                return ResourceManager.GetString("SBP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收缩压2.
        /// </summary>
        internal static string SBP2 {
            get {
                return ResourceManager.GetString("SBP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血清白蛋白.
        /// </summary>
        internal static string SerumAlbumin {
            get {
                return ResourceManager.GetString("SerumAlbumin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血清总蛋白.
        /// </summary>
        internal static string SerumTotalProtein {
            get {
                return ResourceManager.GetString("SerumTotalProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总胆固醇.
        /// </summary>
        internal static string TC {
            get {
                return ResourceManager.GetString("TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 甘油三酯.
        /// </summary>
        internal static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 餐后血糖.
        /// </summary>
        internal static string TwoHPBG {
            get {
                return ResourceManager.GetString("TwoHPBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尿素氮.
        /// </summary>
        internal static string UN {
            get {
                return ResourceManager.GetString("UN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尿Ph.
        /// </summary>
        internal static string UPH {
            get {
                return ResourceManager.GetString("UPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尿蛋白定量.
        /// </summary>
        internal static string UrinaryProtein {
            get {
                return ResourceManager.GetString("UrinaryProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尿糖.
        /// </summary>
        internal static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尿尿酸.
        /// </summary>
        internal static string UUA {
            get {
                return ResourceManager.GetString("UUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 腰围.
        /// </summary>
        internal static string WC {
            get {
                return ResourceManager.GetString("WC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 体重.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
