//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSS.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatisticsForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatisticsForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDSS.Resource.StatisticsForm", typeof(StatisticsForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均值.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对照组.
        /// </summary>
        internal static string ContrastGroup {
            get {
                return ResourceManager.GetString("ContrastGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        internal static string DefinedOwn {
            get {
                return ResourceManager.GetString("DefinedOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 诊断参数.
        /// </summary>
        internal static string dignoParas {
            get {
                return ResourceManager.GetString("dignoParas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每月.
        /// </summary>
        internal static string EveryMonth {
            get {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每季度.
        /// </summary>
        internal static string EverySeason {
            get {
                return ResourceManager.GetString("EverySeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每年.
        /// </summary>
        internal static string EveryYear {
            get {
                return ResourceManager.GetString("EveryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组别.
        /// </summary>
        internal static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大值.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中位数.
        /// </summary>
        internal static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小值.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 患病人数.
        /// </summary>
        internal static string Morbid {
            get {
                return ResourceManager.GetString("Morbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 患病率.
        /// </summary>
        internal static string MorbidRate {
            get {
                return ResourceManager.GetString("MorbidRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新发人数.
        /// </summary>
        internal static string NewMorbid {
            get {
                return ResourceManager.GetString("NewMorbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发病率.
        /// </summary>
        internal static string NewMorbidRate {
            get {
                return ResourceManager.GetString("NewMorbidRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        internal static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 达标人数.
        /// </summary>
        internal static string Qualified {
            get {
                return ResourceManager.GetString("Qualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 达标率.
        /// </summary>
        internal static string QualifiedRate {
            get {
                return ResourceManager.GetString("QualifiedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四分差.
        /// </summary>
        internal static string Quar {
            get {
                return ResourceManager.GetString("Quar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准差.
        /// </summary>
        internal static string StandardDeviation {
            get {
                return ResourceManager.GetString("StandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计组.
        /// </summary>
        internal static string StatisticGroup {
            get {
                return ResourceManager.GetString("StatisticGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数值参数.
        /// </summary>
        internal static string valueParas {
            get {
                return ResourceManager.GetString("valueParas", resourceCulture);
            }
        }
    }
}
